# Playbook

- hosts: all
  vars:
    ansible_connection: community.aws.aws_ssm
    ansible_aws_ssm_region: us-wast-1 # substitute for your region
  tasks:
    - name: test
      command:
        cmd: ls -l
