---
- hosts: all
  become: yes
  become_user: root
  vars:
    ansible_connection: community.aws.aws_ssm
    ansible_aws_ssm_bucket_name: ajpolly
    ansible_aws_ssm_region: ap-south-1
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: install apache2
      apt: name=apache2 state=latest
