# Playbook

- hosts: all
  become: yes
  become_user: root
  vars:
    ansible_connection: community.aws.aws_ssm
    ansible_aws_ssm_bucket_name: ajpolly2
    ansible_aws_ssm_region: us-east-1
    ansible_python_interpreter: /usr/bin/python3
    ansible_aws_ssm_plugin: /bin/bash
    
  tasks:
    - name: test
      command:
        cmd: ls -l
