---
- name: Converge
  hosts: all
  tasks:
    - name: "Include acme.my_new_role"
      include_role:
        name: "acme.my_new_role"
    - name: including role
      env:
        ANSIBLE_ROLES_PATH: "../../../roles"
